package com.gcll.ticketagent.agent;

public enum AgentStepName {
    SUBMITTED,
    PREPROCESS,
    TICKET_EXTRACT,
    INFO_GAP_ANALYSIS,
    COMPLETENESS_DECISION,
    FOLLOW_UP_QUESTION_GENERATE,
    AGENT_PLAN,
    KNOWLEDGE_SEARCH,
    TOOL_SELECTION,
    EVIDENCE_COLLECTION,
    ROOT_CAUSE_ANALYSIS,
    PRIORITY_EVALUATION,
    TEAM_ROUTING,
    SUGGESTION_GENERATION,
    WAIT_HUMAN_CONFIRM,
    FINAL
}
