DELETE FROM ops_metric_sample;
DELETE FROM ops_log_sample;
DELETE FROM knowledge_document;

INSERT INTO knowledge_document (id, source_type, source_id, title, content, system_name, module_name, tags)
VALUES
('kd-001', 'SOP', 'sop-pay-callback-001', '支付回调失败处理 SOP',
 '生产环境支付回调 /pay/callback 返回 500 时，先查接口错误日志，检查 payment_callback_log 回调处理状态，检查 MQ 消费积压和死信队列，检查订单补偿任务。若涉及多用户或资金状态不一致，按 P1 处理并进入人工确认。',
 '支付系统', '支付回调', '["支付","回调","500","订单"]'),
('kd-002', 'REDMINE', 'rm-8821', '支付成功订单状态未更新',
 '现象：用户支付成功但订单仍为待支付。原因：回调处理失败或 MQ 消费异常。方案：检查回调日志、订单补偿任务、支付成功事件消费位点。',
 '支付系统', '支付回调', '["订单","待支付","MQ"]'),
('kd-003', 'RUNBOOK', 'rb-payment-oom-001', 'payment-service OOMKilled Runbook',
 '当 payment-service Pod OOMKilled 时，先确认容器内存 limit 与工作集曲线，检查最近发布、批量任务、缓存对象增长和 JVM heap dump。若生产多用户支付失败，先扩容或回滚，再分析泄漏。',
 '支付系统', '支付服务', '["OOM","K8s","内存","Runbook"]'),
('kd-004', 'INCIDENT', 'inc-2026-0412', '支付服务缓存击穿导致内存上涨',
 '历史故障：促销期间支付服务本地缓存未设置最大容量，热点 key 扩散导致 heap usage 持续升高，最终 OOMKilled。处理：限流、回滚缓存策略、补充 Caffeine maximumSize。',
 '支付系统', '支付服务', '["缓存","OOM","促销"]'),
('kd-005', 'SOP', 'sop-db-pool-001', '数据库连接池耗尽排查 SOP',
 'HikariPool 连接不可用或等待线程快速升高时，检查慢 SQL、未关闭连接、事务过长、连接池 maxPoolSize、数据库活跃连接和锁等待。生产核心链路受影响时按 P1 处理。',
 '订单系统', '数据库连接池', '["DB","HikariCP","连接池","Timeout"]'),
('kd-006', 'REDMINE', 'rm-9134', '订单查询慢 SQL 导致连接池耗尽',
 '现象：order-service HikariPool active 达到 50，waiting 线程增加。原因：订单列表查询缺少联合索引，事务持有连接过久。方案：加索引、降低事务范围、临时扩容连接池。',
 '订单系统', '订单查询', '["慢SQL","连接池","索引"]'),
('kd-007', 'SOP', 'sop-mfa-001', 'MFA 重置 SOP',
 'MFA 重置必须先查询用户状态和最近登录风险，需管理员审批后执行。普通账号单用户问题默认 P3；涉及管理员批量无法登录时升级到 P1/P2。',
 '账号系统', 'MFA', '["MFA","账号","权限"]'),
('kd-008', 'RUNBOOK', 'rb-permission-001', '权限开通失败排查 Runbook',
 '权限开通失败先确认用户、角色、租户、审批单状态和权限同步任务。若仅单用户测试环境问题，优先级低；若生产批量权限同步失败，需要升级。',
 '账号系统', '权限', '["权限","审批","同步"]'),
('kd-009', 'INCIDENT', 'inc-2026-0508', '库存扣减成功但订单未更新',
 '数据一致性问题：库存服务扣减成功后订单服务消费失败，导致订单状态未同步。需检查 outbox 表、MQ 死信、补偿任务和幂等消费记录。',
 '订单系统', '数据一致性', '["数据不一致","MQ","补偿"]'),
('kd-010', 'SOP', 'sop-mq-lag-001', 'MQ 消费积压排查 SOP',
 '当支付成功事件或订单事件积压时，检查 consumer lag、死信队列、消费异常日志、实例数和下游数据库耗时。涉及核心交易链路时按 P1。',
 '中间件平台', '消息队列', '["MQ","积压","死信"]'),
('kd-011', 'RUNBOOK', 'rb-cache-timeout-001', 'Redis 缓存超时排查 Runbook',
 'Redis 超时先检查连接池、慢查询、热点 key、大 key、网络抖动和 Redis CPU。若缓存不可用导致核心链路降级失败，需要快速切换降级策略。',
 '基础平台', 'Redis', '["Redis","缓存","超时"]'),
('kd-012', 'ERROR_CODE', 'err-pay-500-callback', '支付回调 500 常见错误码',
 'PAY-CALLBACK-500 通常与签名校验失败、回调幂等冲突、数据库连接异常或 MQ 发布失败有关。需要结合日志 traceId 和 payment_callback_log 状态确认。',
 '支付系统', '支付回调', '["错误码","PAY-CALLBACK-500"]'),
('kd-013', 'SOP', 'sop-test-env-p3', '测试环境单用户故障优先级规则',
 '测试环境、单用户、可绕过且不影响发布窗口的问题一般评为 P3。若阻塞验收或影响发布窗口，可提升到 P2。',
 '通用', '优先级', '["P3","测试环境"]'),
('kd-014', 'INCIDENT', 'inc-2026-0601', '结算任务重复执行导致账务差异',
 '结算批任务重复执行导致账务差异，需立即冻结相关批次，核对流水、幂等表和补偿记录。资金相关数据不一致默认至少 P1 并需要人工确认。',
 '结算系统', '批处理', '["资金","数据不一致","幂等"]'),
('kd-015', 'RUNBOOK', 'rb-no-hit-001', '知识库无命中处理规范',
 '当知识库无相似案例命中时，Agent 必须明确标注无历史来源，转向日志、指标和人工补充信息，不得编造历史案例。',
 '通用', '知识库', '["无命中","可信输出"]');

INSERT INTO ops_log_sample (id, system_name, service_name, module_name, environment, level, occurred_at, trace_id, message, tags)
VALUES
('log-001', '支付系统', 'payment-service', '支付服务', 'prod', 'ERROR', '2026-06-11 10:23:15', 'trace-pay-oom-001',
 'Java heap space: OutOfMemoryError; Pod payment-service-7b8c9d4-x2k9 terminated with OOMKilled exit code 137; memory limit 512Mi, usage before kill 524Mi.',
 '["OOM","K8s","payment-service"]'),
('log-002', '支付系统', 'payment-service', '支付服务', 'prod', 'WARN', '2026-06-11 10:21:42', 'trace-pay-oom-001',
 'Local cache paymentRiskCache size increased to 245000 entries after promotion traffic spike.',
 '["cache","memory"]'),
('log-003', '订单系统', 'order-service', '数据库连接池', 'prod', 'WARN', '2026-06-11 10:15:32', 'trace-order-db-001',
 'HikariPool-1 - Connection is not available, request timed out after 30000ms; active=50 idle=0 waiting=23 max=50.',
 '["HikariCP","connection-timeout"]'),
('log-004', '订单系统', 'order-service', '订单查询', 'prod', 'ERROR', '2026-06-11 10:15:34', 'trace-order-db-001',
 'Slow SQL detected: SELECT * FROM orders WHERE status=PENDING FOR UPDATE cost=28450ms.',
 '["slow-sql","lock"]'),
('log-005', '支付系统', 'payment-callback', '支付回调', 'prod', 'ERROR', '2026-06-11 10:05:11', 'trace-pay-cb-001',
 '/pay/callback returned 500; payment_callback_log status=FAILED; publish payment_success_event failed.',
 '["callback","500","MQ"]'),
('log-006', '账号系统', 'account-service', 'MFA', 'prod', 'INFO', '2026-06-11 09:05:11', 'trace-mfa-001',
 'MFA reset request created for user u-8831; waiting admin approval.',
 '["MFA","approval"]'),
('log-007', '结算系统', 'settlement-job', '批处理', 'prod', 'ERROR', '2026-06-11 02:31:00', 'trace-settle-001',
 'Duplicate settlement batch detected: batchNo=SETTLE-20260610 already processed, idempotency record missing.',
 '["settlement","idempotency"]');

INSERT INTO ops_metric_sample (id, system_name, service_name, metric_name, environment, occurred_at, metric_value, unit, labels, status)
VALUES
('metric-001', '支付系统', 'payment-service', 'container_memory_working_set_mib', 'prod', '2026-06-11 10:20:00', 412, 'Mi', '{"pod":"payment-service-7b8c9d4-x2k9"}', 'rising'),
('metric-002', '支付系统', 'payment-service', 'container_memory_working_set_mib', 'prod', '2026-06-11 10:21:00', 467, 'Mi', '{"pod":"payment-service-7b8c9d4-x2k9"}', 'rising'),
('metric-003', '支付系统', 'payment-service', 'container_memory_working_set_mib', 'prod', '2026-06-11 10:22:00', 501, 'Mi', '{"pod":"payment-service-7b8c9d4-x2k9"}', 'near_limit'),
('metric-004', '支付系统', 'payment-service', 'container_memory_working_set_mib', 'prod', '2026-06-11 10:23:00', 524, 'Mi', '{"pod":"payment-service-7b8c9d4-x2k9","limit":"512Mi"}', 'oom_killed'),
('metric-005', '订单系统', 'order-service', 'hikaricp_connections_active', 'prod', '2026-06-11 10:12:00', 30, 'count', '{"pool":"HikariPool-1","max":"50"}', 'normal'),
('metric-006', '订单系统', 'order-service', 'hikaricp_connections_active', 'prod', '2026-06-11 10:13:00', 38, 'count', '{"pool":"HikariPool-1","max":"50"}', 'rising'),
('metric-007', '订单系统', 'order-service', 'hikaricp_connections_active', 'prod', '2026-06-11 10:14:00', 45, 'count', '{"pool":"HikariPool-1","max":"50"}', 'high'),
('metric-008', '订单系统', 'order-service', 'hikaricp_connections_active', 'prod', '2026-06-11 10:15:00', 50, 'count', '{"pool":"HikariPool-1","max":"50","waiting":"23"}', 'exhausted'),
('metric-009', '支付系统', 'payment-callback', 'http_server_errors', 'prod', '2026-06-11 10:05:00', 37, 'count', '{"uri":"/pay/callback","status":"500"}', 'error_spike'),
('metric-010', '结算系统', 'settlement-job', 'duplicate_batch_count', 'prod', '2026-06-11 02:31:00', 2, 'count', '{"batchNo":"SETTLE-20260610"}', 'duplicate');
