apiVersion: v1
kind: Service
metadata:
  name: tech-support-agent
  labels:
    app: tech-support-agent
spec:
  type: NodePort
  selector:
    app: tech-support-agent
  ports:
    - name: http
      port: 8020
      targetPort: 8020
      nodePort: 30020
